/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Exception.NotValidNameSeted;
import Logica.RaceStatus;
import java.util.Random;
import java.util.concurrent.CountDownLatch;
import javax.swing.JOptionPane;
import Logica.RuningHorse;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author byron
 */
public class FrmMainHorseRace extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMainHorseRace.class.getName());
    private Random r = new Random();
    //private final String names[]  = {"Juan", "Jonathan", "Daniel", "Tiro al Blanco", "Morph"};
    private ArrayList<String> names;
    private RaceStatus raceStatus;
    private CountDownLatch sameStart;
    private CountDownLatch latch;
    private RuningHorse runner[];
    private boolean manualnameOneSetStatus = false;
    private boolean manualnameTwoSetStatus = false;
    private String manualHorseOneName;
    private String manualHorseTwoName;
    private boolean drawStatus = false;

    /**
     * Creates new form FrmMainHorseRace
     */
    public FrmMainHorseRace() {
        initComponents();
        setTitle("Horse Race Game");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblYerHorse = new javax.swing.JLabel();
        lblHorseTwo = new javax.swing.JLabel();
        lblThirdHorse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHorseName = new javax.swing.JTextField();
        bntStartRace = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnbHorseOneName = new javax.swing.JMenuItem();
        mnbHorseTwoName = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblYerHorse.setText("Your Horse");

        lblHorseTwo.setText("Rival Horse");

        lblThirdHorse.setText("Seccond Rival");

        jLabel4.setFont(new java.awt.Font("CaskaydiaCove NFM", 0, 14)); // NOI18N
        jLabel4.setText("Race Camp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThirdHorse)
                            .addComponent(lblHorseTwo)
                            .addComponent(lblYerHorse)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addComponent(lblHorseTwo)
                .addGap(56, 56, 56)
                .addComponent(lblYerHorse)
                .addGap(49, 49, 49)
                .addComponent(lblThirdHorse)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        txtHorseName.setText("Set yer horse name here");
        txtHorseName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHorseNameMouseClicked(evt);
            }
        });

        bntStartRace.setText("Start Race");
        bntStartRace.addActionListener(this::bntStartRaceActionPerformed);

        jMenu1.setText("Set Names");

        mnbHorseOneName.setText("Horse One Name");
        mnbHorseOneName.addActionListener(this::mnbHorseOneNameActionPerformed);
        jMenu1.add(mnbHorseOneName);

        mnbHorseTwoName.setText("Horse Two Name");
        mnbHorseTwoName.addActionListener(this::mnbHorseTwoNameActionPerformed);
        jMenu1.add(mnbHorseTwoName);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(txtHorseName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(bntStartRace, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorseName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntStartRace, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHorseNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHorseNameMouseClicked
        if (txtHorseName.getText().equals("Set yer horse name here")) {
            txtHorseName.setText("");
        }
    }//GEN-LAST:event_txtHorseNameMouseClicked

    private void bntStartRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStartRaceActionPerformed

        Race();

        //Evaluates Draws if is a Draws show it and kill the proccess
        //Evaluates winner
            /**
             * lamda function evaluates winner after waitting horses that finish
             * the race
             */
            new Thread(() -> {

                try {
                    latch.await();

                    SwingUtilities.invokeLater(() -> {
                        winnerGetter();
                    });
                } catch (InterruptedException e) {
                    System.out.println("Error:" + e.getMessage());
                }
            }).start();
        
    }//GEN-LAST:event_bntStartRaceActionPerformed

    private void mnbHorseOneNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbHorseOneNameActionPerformed
        //System.out.println("Hello");
        manualnameOneSetStatus = true;
        manualHorseOneName = JOptionPane.showInputDialog("Nombre del caballo #1");
        System.out.println("Hello " + manualHorseOneName);
    }//GEN-LAST:event_mnbHorseOneNameActionPerformed

    private void mnbHorseTwoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbHorseTwoNameActionPerformed
        manualnameTwoSetStatus = true;
        manualHorseTwoName = JOptionPane.showInputDialog("Nombre del caballo #2");
    }//GEN-LAST:event_mnbHorseTwoNameActionPerformed

    private void declare() {
        raceStatus = new RaceStatus();
        sameStart = new CountDownLatch(1);
        latch = new CountDownLatch(raceStatus.PLAYERS_QUANT);

    }

    private void Race() {
        declare();
        //getClientHorseName();

        if (getClientHorseName()) {

            if (!manualnameOneSetStatus && !manualnameTwoSetStatus) {
                //n[] = {"Juan", "Jonathan", "Daniel", "Tiro al Blanco", "Morph"};
                this.names = new ArrayList<>(List.of("Juan", "Jonathan", "Daniel", "Tiro al Blanco", "Morph"));
                names = generateHorseNames();
            } else if (manualnameOneSetStatus && manualnameTwoSetStatus) {
                //String names[] = {manualHorseOneName, manualHorseTwoName};
                this.names = new ArrayList<>(List.of(manualHorseOneName, manualHorseTwoName));
            } else if (manualnameOneSetStatus || manualnameTwoSetStatus) {
                JOptionPane.showMessageDialog(this,
                        "Debes ingresar ambos nombres",
                        "Agregar Nombres",
                        JOptionPane.ERROR_MESSAGE);
            }
            runner = new RuningHorse[raceStatus.PLAYERS_QUANT];
            //labelInsert();
            for (int i = 0; i < RaceStatus.PLAYERS_QUANT; i++) {
                if (i == 0) {
                    runner[i] = new RuningHorse(txtHorseName.getText().trim(),
                            raceStatus,
                            sameStart,
                            latch
                    );
                    labelInsert(i);
                    runner[i].start();
                    continue;
                }
                runner[i] = new RuningHorse(names.get(i - 1),
                        raceStatus,
                        sameStart,
                        latch
                );
                labelInsert(i);
                runner[i].start();
            }

            sameStart.countDown();
        }

    }

    private void labelInsert(int i) {

        switch (i) {
            case 0 -> {
                runner[i].setHorseShower(lblYerHorse);
            }
            case 1 -> {
                runner[i].setHorseShower(lblHorseTwo);
            }
            case 2 -> {
                runner[i].setHorseShower(lblThirdHorse);
            }

        }

    }

    private void drawGetter() {

        //names
        String n0 = runner[0].getHORSE_NAME();
        String n1 = runner[1].getHORSE_NAME();
        String n2 = runner[2].getHORSE_NAME();

        //times
        double t0 = runner[0].getFinishedTime();
        double t1 = runner[1].getFinishedTime();
        double t2 = runner[2].getFinishedTime();

        if (t0 == t1) {
            JOptionPane.showMessageDialog(this,
                    "Empate \n"
                    + n0 + " y " + n1
                    + "times \n"
                    + n0 + " : " + t0 + ", "
                    + n1 + " : " + t1 + ", "
                    + n2 + " : " + t2 + ", ",
                    "Draw",
                    JOptionPane.DEFAULT_OPTION);
            drawStatus = true;
        } else if (t2 == t0) {
            JOptionPane.showMessageDialog(this,
                    "Empate \n"
                    + n0 + " y " + n2
                    + "times \n"
                    + n0 + " : " + t0 + ", "
                    + n1 + " : " + t1 + ", "
                    + n2 + " : " + t2 + ", ",
                    "Draw",
                    JOptionPane.DEFAULT_OPTION);
            drawStatus = true;
        } else if (t2 == t1) {
            JOptionPane.showMessageDialog(this,
                    "Empate \n"
                    + n1 + " y " + n2
                    + "times \n"
                    + n0 + " : " + t0 + ", "
                    + n1 + " : " + t1 + ", "
                    + n2 + " : " + t2 + ", ",
                    "Draw",
                    JOptionPane.DEFAULT_OPTION);
            drawStatus = true;
        }else if (t2 == t1 && t2 == t0){
                        JOptionPane.showMessageDialog(this,
                    "Empate \n"
                    + n1 + ", " + n2 + " y " + n0
                    + "times \n"
                    + n0 + " : " + t0 + ", "
                    + n1 + " : " + t1 + ", "
                    + n2 + " : " + t2 + ", ",
                    "Draw",
                    JOptionPane.DEFAULT_OPTION);
            drawStatus = true;
        }

    }

//    private boolean isDraw() {
//        new Thread(() -> {
//
//            try {
//                latch.await();
//
//                SwingUtilities.invokeLater(() -> {
//                    drawGetter();
//                });
//            } catch (InterruptedException e) {
//                System.out.println("Error:" + e.getMessage());
//            }
//        }).start();
//
//        return drawStatus;
//
//    }

    private void winnerGetter() {

        if (runner[0].getFinishedTime() < runner[1].getFinishedTime()
                && runner[0].getFinishedTime() < runner[2].getFinishedTime()) {
            JOptionPane.showMessageDialog(this,
                    "Winner: " + runner[0].getHORSE_NAME()
                    + "\n with time: "
                    + runner[0].getFinishedTime()
                    + "\n Horse #2 time: " + " (" + runner[1].getHORSE_NAME() + ") "
                    + runner[1].getFinishedTime()
                    + "\n Horse #3 time: " + " (" + runner[1].getHORSE_NAME() + ") "
                    + runner[2].getFinishedTime(),
                    "Race Finished", JOptionPane.DEFAULT_OPTION);
        } else if (runner[1].getFinishedTime() < runner[0].getFinishedTime()
                && runner[1].getFinishedTime() < runner[2].getFinishedTime()) {
            JOptionPane.showMessageDialog(this,
                    "Winner: " + runner[1].getHORSE_NAME()
                    + "\n with time: "
                    + runner[1].getFinishedTime()
                    + "\n Yer Horse time: " + " (" + runner[0].getHORSE_NAME() + ") "
                    + runner[0].getFinishedTime()
                    + "\n Horse #3 time: " + " (" + runner[2].getHORSE_NAME() + ") "
                    + runner[2].getFinishedTime(),
                    "Race Finished", JOptionPane.DEFAULT_OPTION);
        } else if (runner[2].getFinishedTime() < runner[0].getFinishedTime()
                && runner[2].getFinishedTime() < runner[1].getFinishedTime()) {
            JOptionPane.showMessageDialog(this,
                    "Winner: " + runner[2].getHORSE_NAME()
                    + "\n with time: "
                    + runner[2].getFinishedTime()
                    + "\n Yer Horse time: " + " (" + runner[0].getHORSE_NAME() + ") "
                    + runner[0].getFinishedTime()
                    + "\n Horse #3 time: " + " (" + runner[1].getHORSE_NAME() + ") "
                    + runner[1].getFinishedTime(),
                    "Race Finished", JOptionPane.DEFAULT_OPTION);
        }else{
            drawGetter();
        }

    }

    private boolean getClientHorseName() {
        boolean c = false;
        try {
            if (txtHorseName.getText().trim().equals("Set yer horse name here")
                    || txtHorseName.getText().isBlank()) {
                throw new NotValidNameSeted("Debe ingresar un nombre");
            }
            c = true;
        } catch (NotValidNameSeted e) {
            JOptionPane.showConfirmDialog(this,
                    "Error:" + e.getMessage(),
                    "Atencion",
                    JOptionPane.ERROR_MESSAGE
            );
        }

        return c;

    }

//generate random names for contrincant horses 
    private ArrayList<String> generateHorseNames() {
        ArrayList<String> horseNames = new ArrayList<>();
        for (int i = 0; i < 2; i++) {
            int random = r.nextInt(names.size());
            horseNames.add(i, names.get(random));
        }

        if (horseNames.get(0) != horseNames.get(1)) {
            return horseNames;
        }

        return generateHorseNames();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMainHorseRace().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntStartRace;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHorseTwo;
    private javax.swing.JLabel lblThirdHorse;
    private javax.swing.JLabel lblYerHorse;
    private javax.swing.JMenuItem mnbHorseOneName;
    private javax.swing.JMenuItem mnbHorseTwoName;
    private javax.swing.JTextField txtHorseName;
    // End of variables declaration//GEN-END:variables
}
