/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Exception.NotValidNameSeted;
import Logica.Horse;
import Logica.HorseRace;
import Logica.HorseSkill;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author byron
 */
public class FrmMainHorseRace extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMainHorseRace.class.getName());
    private Horse iaHorseOne;
    private Horse iaHorseTwo;
    private Horse myHorse;
    private HorseRace race;
    private Random r = new Random();
    private final String names[] = {"Juan", "Pedro", "Daniel vibe Coder", "Tiro al Blanco", "Morph"};
    
    
    
    /**
     * Creates new form FrmMainHorseRace
     */
    public FrmMainHorseRace() {
        initComponents();
        setTitle("Horse Race Game");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblYerHorse = new javax.swing.JLabel();
        lblHorseTwo = new javax.swing.JLabel();
        lblThirdHorse = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTimeHorseOne = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHorseName = new javax.swing.JTextField();
        bntStartRace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblYerHorse.setText("Your Horse");

        lblHorseTwo.setText("Rival Horse");

        lblThirdHorse.setText("Seccond Rival");

        jLabel1.setFont(new java.awt.Font("CaskaydiaCove NFM", 0, 18)); // NOI18N
        jLabel1.setText("Times : ");

        lblTimeHorseOne.setText("Horse One");

        jLabel2.setText("Yer Horse");

        jLabel3.setText("Third Horse");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(lblTimeHorseOne)
                .addGap(183, 183, 183)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeHorseOne)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("CaskaydiaCove NFM", 0, 14)); // NOI18N
        jLabel4.setText("Race Camp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYerHorse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorseTwo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThirdHorse, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(84, 84, 84)
                .addComponent(lblHorseTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(lblYerHorse)
                .addGap(89, 89, 89)
                .addComponent(lblThirdHorse)
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtHorseName.setText("Set yer horse name here");
        txtHorseName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHorseNameMouseClicked(evt);
            }
        });

        bntStartRace.setText("Start Race");
        bntStartRace.addActionListener(this::bntStartRaceActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(txtHorseName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(bntStartRace, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorseName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntStartRace, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHorseNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHorseNameMouseClicked
        if (txtHorseName.getText().equals("Set yer horse name here")) {
            txtHorseName.setText("");
        }
    }//GEN-LAST:event_txtHorseNameMouseClicked

    private void bntStartRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStartRaceActionPerformed
        // TODO add your handling code here:
        declare();
        System.out.println("We are here : " + iaHorseOne.getHorseName() + " and " + iaHorseTwo.getHorseName());


    }//GEN-LAST:event_bntStartRaceActionPerformed

    private void declare() {
        String hnames[] = generateHorseNames();
        iaHorseOne = new Horse();
        iaHorseTwo = new Horse();
        iaHorseOne.setHorseName(hnames[0]);
        iaHorseTwo.setHorseName(hnames[1]);

        getClientHorseName();

        race = new HorseRace(myHorse, iaHorseOne, iaHorseTwo);

    }

    private void getClientHorseName() {

        try {
            if (!(txtHorseName.getText().equals("Set yer horse name here")
                    || txtHorseName.getText().isBlank())) {
                throw new NotValidNameSeted("Debe ingresar un nombre");
            }
            myHorse = new Horse();
            myHorse.setHorseName(txtHorseName.getText().trim());
        } catch (NotValidNameSeted e) {
            JOptionPane.showConfirmDialog(this,
                    "Error:" + e.getMessage(),
                    "Atencion",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }

//generate random names for contrincant horses 

    private String[] generateHorseNames() {
        String horseNames[] = new String[2];
        for (int i = 0; i < 2; i++) {
            int random = r.nextInt(0, 5);
            horseNames[i] = names[random];
        }
        
        if (horseNames[0] != horseNames[1]){
            return horseNames;
        }
        
        return generateHorseNames();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMainHorseRace().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntStartRace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHorseTwo;
    private javax.swing.JLabel lblThirdHorse;
    private javax.swing.JLabel lblTimeHorseOne;
    private javax.swing.JLabel lblYerHorse;
    private javax.swing.JTextField txtHorseName;
    // End of variables declaration//GEN-END:variables
}
